from os import listdir
from os.path import dirname, abspath, join, splitext

from django.core.management.base import BaseCommand

HEADER = '''/* FLAGS auto-generated by %s */
.flag {
  width: 16px;
  height: 11px;
  background-image: url(images/flags/missing.png);
}
'''

ENTRY = '''.flag.%s {
  background-image: url(images/flags/%s);
}
'''

class Command(BaseCommand):
    help = "Auto-generates flags.css from"

    def handle(self, *args, **options):
        static_dir_path = join(dirname(dirname((dirname(abspath(__file__))))),
                               'static')
        flag_dir_path = join(static_dir_path, 'images', 'flags')
        css_file_path = join(static_dir_path, 'flags.css')

        # open css file
        css_file = open(css_file_path, 'w')
        css_file.write(HEADER % __name__)

        for f in listdir(flag_dir_path):
            if f.endswith('.png'):
                css_file.write(ENTRY % (splitext(f)[0], f))

        css_file.close()
